// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[4] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff,
                 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  syscall(__NR_prctl, 0xcul, 3ul, 0, 0, 0);
  memcpy((void*)0x200004c0, "/dev/loop#\000", 11);
  res = -1;
  res = syz_open_dev(0x200004c0, 0, 0x40440);
  if (res != -1)
    r[0] = res;
  syscall(__NR_flistxattr, r[0], 0x200000c0ul, 0x5aul);
  *(uint32_t*)0x20000080 = 1;
  *(uint32_t*)0x20000084 = 0x80;
  *(uint8_t*)0x20000088 = 0;
  *(uint8_t*)0x20000089 = 0;
  *(uint8_t*)0x2000008a = 0;
  *(uint8_t*)0x2000008b = 0;
  *(uint32_t*)0x2000008c = 0;
  *(uint64_t*)0x20000090 = 0x1f;
  *(uint64_t*)0x20000098 = 0x1c112;
  *(uint64_t*)0x200000a0 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200000a8, 0, 38, 26);
  *(uint32_t*)0x200000b0 = 0;
  *(uint32_t*)0x200000b4 = 0;
  *(uint64_t*)0x200000b8 = 0;
  *(uint64_t*)0x200000c0 = 0;
  *(uint64_t*)0x200000c8 = 0;
  *(uint64_t*)0x200000d0 = 0;
  *(uint32_t*)0x200000d8 = 0;
  *(uint32_t*)0x200000dc = 0;
  *(uint64_t*)0x200000e0 = 0;
  *(uint32_t*)0x200000e8 = 0;
  *(uint16_t*)0x200000ec = 0;
  *(uint16_t*)0x200000ee = 0;
  *(uint32_t*)0x200000f0 = 0;
  *(uint32_t*)0x200000f4 = 0;
  *(uint64_t*)0x200000f8 = 0;
  syscall(__NR_perf_event_open, 0x20000080ul, 0, 0ul, -1, 0ul);
  memcpy((void*)0x200004c0, "/dev/loop#\000", 11);
  res = -1;
  res = syz_open_dev(0x200004c0, 0, 0);
  if (res != -1)
    r[1] = res;
  syscall(__NR_ioctl, r[1], 0x40081271, 0ul);
  *(uint32_t*)0x200001c0 = 0x1d;
  *(uint32_t*)0x200001c4 = 7;
  *(uint64_t*)0x200001c8 = 0x20000000;
  *(uint8_t*)0x20000000 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x20000001, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000001, 0, 4, 4);
  *(uint16_t*)0x20000002 = 0;
  *(uint32_t*)0x20000004 = 0x400;
  *(uint8_t*)0x20000008 = 0;
  *(uint8_t*)0x20000009 = 0;
  *(uint16_t*)0x2000000a = 0;
  *(uint32_t*)0x2000000c = 1;
  *(uint8_t*)0x20000010 = 0x18;
  STORE_BY_BITMASK(uint8_t, , 0x20000011, 8, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000011, 6, 4, 4);
  *(uint16_t*)0x20000012 = 0;
  *(uint32_t*)0x20000014 = 8;
  *(uint8_t*)0x20000018 = 0;
  *(uint8_t*)0x20000019 = 0;
  *(uint16_t*)0x2000001a = 0;
  *(uint32_t*)0x2000001c = 7;
  *(uint8_t*)0x20000020 = 0x85;
  STORE_BY_BITMASK(uint8_t, , 0x20000021, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000021, 1, 4, 4);
  *(uint16_t*)0x20000022 = 0;
  *(uint32_t*)0x20000024 = 3;
  *(uint8_t*)0x20000028 = 0x85;
  STORE_BY_BITMASK(uint8_t, , 0x20000029, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x20000029, 2, 4, 4);
  *(uint16_t*)0x2000002a = 0;
  *(uint32_t*)0x2000002c = 3;
  *(uint8_t*)0x20000030 = 0x95;
  *(uint8_t*)0x20000031 = 0;
  *(uint16_t*)0x20000032 = 0;
  *(uint32_t*)0x20000034 = 0;
  *(uint64_t*)0x200001d0 = 0x20000040;
  memcpy((void*)0x20000040, "GPL\000", 4);
  *(uint32_t*)0x200001d8 = 0;
  *(uint32_t*)0x200001dc = 0x2b;
  *(uint64_t*)0x200001e0 = 0x20000080;
  *(uint32_t*)0x200001e8 = 0x40f00;
  *(uint32_t*)0x200001ec = 0x14;
  memset((void*)0x200001f0, 0, 16);
  *(uint32_t*)0x20000200 = 0;
  *(uint32_t*)0x20000204 = 0x1b;
  *(uint32_t*)0x20000208 = -1;
  *(uint32_t*)0x2000020c = 8;
  *(uint64_t*)0x20000210 = 0x20000140;
  *(uint32_t*)0x20000140 = 9;
  *(uint32_t*)0x20000144 = 4;
  *(uint32_t*)0x20000218 = 8;
  *(uint32_t*)0x2000021c = 0x10;
  *(uint64_t*)0x20000220 = 0x20000180;
  *(uint32_t*)0x20000180 = 1;
  *(uint32_t*)0x20000184 = 1;
  *(uint32_t*)0x20000188 = -1;
  *(uint32_t*)0x2000018c = 0x5346;
  *(uint32_t*)0x20000228 = 0x10;
  *(uint32_t*)0x2000022c = -1;
  *(uint32_t*)0x20000230 = 0;
  *(uint32_t*)0x20000234 = 0;
  *(uint64_t*)0x20000238 = 0;
  res = syscall(__NR_bpf, 5ul, 0x200001c0ul, 0x80ul);
  if (res != -1)
    r[2] = res;
  syscall(__NR_ioctl, r[1], 0x4c00, r[2]);
  memcpy((void*)0x20000040, "/dev/zero\000", 10);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000040ul, 0x601ul, 0ul);
  if (res != -1)
    r[3] = res;
  *(uint64_t*)0x200001c0 = 0;
  *(uint64_t*)0x200001c8 = 0;
  *(uint16_t*)0x200001d0 = 0;
  *(uint16_t*)0x200001d2 = 0;
  *(uint32_t*)0x200001d4 = 0;
  syscall(__NR_ioctl, r[3], 0xc0189436, 0x200001c0ul);
  syscall(__NR_ioctl, r[3], 0x80247009, 0x20000240ul);
}
int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  for (procid = 0; procid < 16; procid++) {
    if (fork() == 0) {
      loop();
    }
  }
  sleep(1000000);
  return 0;
}
